import { Container, Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ApolloClientProvident from './ApolloClientProvider'
import Footer from './_components/Footer'
import Header from './_components/Header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ApolloClientProvident>
          <Theme radius='small'>
            <Header />
            <Container>
              <main>{children}</main>
            </Container>
            <Footer />
          </Theme>
        </ApolloClientProvident>
      </body>
    </html>
  )
}
